title: "CS-7641 Machine Learning Project"
description: "Course Project Website"
theme: minima
author: "Your Name"
plugins:
  - jekyll-seo-tag
  - jekyll-feed

# Navigation
header_pages:
  - proposal.md
  - midterm.md
  - endsem.md
