# Site settings
title: CS-7641 Machine Learning Project
description: Project documentation for CS-7641 Machine Learning course
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Theme - Just the Docs (best for academic/technical documentation)
remote_theme: just-the-docs/just-the-docs@v0.8.2
color_scheme: light

# Enable search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/

# Enable copy button on code blocks
enable_copy_code_button: true

# Navigation structure
nav_order: 1

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "CS-7641 Machine Learning - Georgia Institute of Technology"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/yourusername/yourrepo"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
